name: Create Docker Image CI
on: [push]

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: Build the Docker image
        run: docker build . --file src/dockerfile --tag my-image-name:$(date +%s)
  build2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
