name: Create Docker Image CI
on: [push]

env:
  #REGISTRY: 'ghcr.io/deegbo/argocd-test'
  #IMAGE_NAME: ${{ format('{0}-{1}', github.event.repository.name, github.sha) }}
  #USERNAME: ${{ secrets.USERNAME }}
  DOCKER_TOKEN: ${{ secrets.GITOPS_PAT_TOKEN }}


jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
     
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
     
      #- name: Log in to GHCR
      # run: echo  "${{ secrets.GITOPS_PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          #docker build . --file src/dockerfile --tag my-image-name:$(date +%s)
          docker build . --file src/dockerfile --tag ghcr.io/${{ github.actor }}/argocd-test:latest
          docker push ghcr.io/${{ github.actor }}/argocd-test:latest

      - name: Check for the docker image
        run: docker images
  
  build2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The a ${{ github.event_name }} event."
